SELECT * FROM CUSTOMER; 
SELECT * FROM VEHICLE;
SELECT * FROM FINANCE_AGREEMENT;

-- Select Ammend 
SELECT 
  'A' || TO_CHAR(AGREE_ID) AS AGREEMENT_NO,
  'R ' || TO_CHAR(AMOUNT, 'FM999,999,999') AS AMOUNT,
  TO_CHAR(AGREE_DATE, 'DD FMMonth YYYY') AS AGREE_DATE,
  CUSTOMER_ID,
  VIN
FROM FINANCE_AGREEMENT;
--FMMonth trimes text so correct format enforced 