--sql script save file? 

-- Question 1:
CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(6) PRIMARY KEY,
FULLNAME VARCHAR2(150),
CONTACT NUMBER(10),
EMAIL VARCHAR2(100)
);
CREATE TABLE VEHICLE(
VIN VARCHAR2(17) PRIMARY KEY,  -- VINs are alphanumeric DROP F_A THEN V THEN RECREATE V, F_A
MAKE VARCHAR2(50),
MODEL VARCHAR2(50),
YEAR DATE, -- SET IN INSERT AS TO_DATE('2025', 'YYYY')
MILEAGE NUMBER(10)
);


CREATE TABLE FINANCE_AGREEMENT(
AGREE_ID NUMBER(3) PRIMARY KEY, -- ADD 'A' IN SELECT
AMOUNT NUMBER(10,0), -- 10 DIGETS, NO DECIMALS
AGREE_DATE DATE, 
CUSTOMER_ID NUMBER(6), -- fixed MUST have range! 
VIN VARCHAR2(17),

CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT FK_VEHICLE FOREIGN KEY (VIN) REFERENCES VEHICLE (VIN) 
);

-- Better Select: 
SELECT 
  'A' || TO_CHAR(AGREE_ID) AS AGREEMENT_NO,
  'R ' || TO_CHAR(AMOUNT, 'FM999,999,999') AS AMOUNT,
  TO_CHAR(AGREE_DATE, 'DD FMMonth YYYY') AS AGREE_DATE,
  CUSTOMER_ID,
  VIN
FROM FINANCE_AGREEMENT;
--FMMonth trimes text so correct format enforced 

-- Question 2:
-- TO_CHAR(number, format)
-- 999,999,999 - 9 is digent -> , is for readiblity -> FM like TRIM(C#) as FM: Fill Mode 

-- Q2
SELECT C.FULLNAME AS CUSTOMER, 
FA.VIN, 
'R ' || TO_CHAR(FA.AMOUNT, 'FM999,999,999') AS AMOUNT 
FROM FINANCE_AGREEMENT FA
JOIN CUSTOMER C ON FA.CUSTOMER_ID = C.CUSTOMER_ID;

-- Question 3: 
SELECT 
    C.CUSTOMER_ID, C.EMAIL,
    V.MAKE, V.MODEL,
    FA.AMOUNT, FA.AMOUNT * 0.1 AS DISCOUNT, FA.AMOUNT - (FA.AMOUNT * 0.1) AS "DISCOUNT AMOUNT"
FROM FINANCE_AGREEMENT FA
JOIN CUSTOMER C ON FA.CUSTOMER_ID = C.CUSTOMER_ID
JOIN VEHICLE V ON FA.VIN = V.VIN;